name: CI

on: [push]

jobs:
  compile-and-flash:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Compile and Flash
      uses: theworkflow/particle.io-actions@master
      with:
        access_token: ${{ secrets.PARTICLE_API_TOKEN }}
        device_type: argon
        device_id: CentralHub
